### ISSUE TITLE
[Bug] Forms: dropdowns carets not clickable

### ISSUE THREAD

**Issue by twirlingsky** [telusdigital/tds#267]
In the dropdowns for forms the carets are not currently clickable. Also, in Chrome the dropdown information is not styled, it is coming up grey and appears in front of the label. In Firefox the dropdown information comes up below with a white background.

**Comment by ryanoglesby08** [comment]
Testing this on v1.0, seems like this is still a bug. Reopening this Issue until we release a fix.

**Comment by ryanoglesby08** [comment]
Fixed in [v1.0.3](https://github.com/telusdigital/tds/releases/tag/v1.0.3) and [v0.34.4](https://github.com/telusdigital/tds/releases/tag/v0.34.3)
