### ISSUE TITLE
[Heading.Sup] Overlapping superscript for multi-line headings on mobile viewport

### ISSUE THREAD

**Issue by bernietrinh** [telusdigital/tds#428]
## Description
- On mobile viewport, having multiline text that has a superscript not on the first line will result on the superscript overlap with above text, especially with letters like `g`, `y`, `j`, etc.

Currently, `top: -1rem`, looking for some recommendations in terms of the preferred fix.
 
## Reproduction Steps
- [ ] Create heading that is multiline

## Version Number of TDS
- [ ] 0.29

<img width="446" alt="screen shot 2017-11-16 at 1 25 00 pm" src="https://user-images.githubusercontent.com/6313985/32911790-345112b0-cadb-11e7-85d9-c6c7bb32bf3e.png">

**Comment by theetrain** [comment]
This issue is no longer reproducible within TDS.
