### ISSUE TITLE
TDS Tags and Contentful, ie. Superscript

### ISSUE THREAD

**Issue by TMTelus** [telusdigital/tds#449]
## Description

Superscript for text like Trademark (™) within a header that reads text from Contentful can't use the `Heading.Sup` tag because Contentful doesn't allow TDS code to be embedded in the string. So a string from Contentful like "TELUS Pik TV™ doesn’t play by the rules" can't use the `Heading.Sup` for superscripting the TM.

As a workaround, we're using the ™ glyph instead but for `h1` there seems to be a sizing issue in the font because it's much too big.

## Reproduction Steps

See the header for PikTV:
https://www.telus.com/en/bc/tv/pik/?linktype=nav

## Reproduction Percentage (if applicable)

- 10/10 times

## Meta

- [x] TDS version: v0.32.1
- [ ] Willing to develop solution

**Comment by andrewkumar** [comment]
@theetrain what about applications that do not use Site Builder?

**Comment by lzcabrera** [comment]
@andrekumar the tds .Sup components were released in v0.22.0. Any team using v0.22.0+ can style superscripts using those components.
I think this question is for the Contentful team as to how to structure data within Contentful to consume the available TDS components.

**Comment by theetrain** [comment]
At the time of this comment, Superscript is already available as a sub-component of `Heading` and `DisplayHeading`. This is consumable for developers of TDS in an ordinary React application. 

Please direct further site-builder-related queries to the site builder team. For React usage of Superscript, feel free to leave a comment or re-open this issue.
