### ISSUE TITLE
[Forms] Nested divs in spans produce invalid HTML markup

### ISSUE THREAD

**Issue by ryanoglesby08** [telusdigital/tds#459]
## Description

All components with a `<label>` - Input, Checkbox, Radio, Textarea, Select - have a `<div>` nested within the `<label>`. This is invalid HTML, which impacts accessibility.

## Reproduction Steps

1. Copy the first snapshot from the Input specs: "src/components/Input/_tests/snapshots_/Input.spec.jsx.snap"
2. Paste it into the HTML validator: https://validator.w3.org
3. Click "check"
4. Observe the validation error: "Element div not allowed as child of element label in this context."

## Meta

- TDS version: v0.34 and 1.0
- Low impact

**Comment by ryanoglesby08** [comment]
Core team JIRA link: <https://telusdigital.atlassian.net/browse/TDS-477>

**Comment by lzcabrera** [comment]
Closing this issue.
We just released a fix for this in [v1.0.2](https://github.com/telusdigital/tds/releases/tag/v1.0.2) and [v0.34.2](https://github.com/telusdigital/tds/releases/tag/v0.34.2).
