### ISSUE TITLE
Create a Lazy Loading component

### ISSUE THREAD

**Issue by githubjosh** [telusdigital/tds#460]
## Description

To ensure the fastest possible page loads, we should render content not critical to SEO or the immediate user experience, on the client (browser) not the server.

For example, images below the fold should only be requested when they are in the user's viewport. Same with other page content not related to a page's keyword strategy (e.g., `<aside>Promotions</aside>)` can be loaded after the server rendering.

## Recommendation

Create a Lazy Loading component that wraps other components and in turn renders them only in the browser. This may be as simple as extending an existing NPM library such as `react-lazy-load`

## References
The Accessories team has already implemented lazy loading using the `react-lazy-load` package. 

Example here: https://github.com/telusdigital/telus-digital-life-ra/blob/912c50658581e36d343f3f3ebaaeef6167cbc864/ui/src/components/ProductTemplate/ProductFeatures/index.jsx

**Comment by theetrain** [comment]
Thanks for the suggestion! We agree that lazy loading should be a part of our best practices (as well as reference architecture), but this is currently not in our backlog. 

I suggest developing a lazy loading wrapper internally and then contributing it back to the forthcoming TDS community. If the need for this component is very high, we can work together to accept a contributing here in the core.

**Comment by ryanoglesby08** [comment]
@githubjosh I think this has been created in isomorphic-core now? Is this the [`AsyncComponent`](https://github.com/telusdigital/isomorphic-core#asynccomponent)?

Maybe at some point it could be moved into tds-community? But maybe for now we close this issue?

**Comment by githubjosh** [comment]
The npm library react-lazy-load now wraps the ResponsiveImage component in the Redux-Contentful library. 

Can probably close this issue. Thanks.
