### ISSUE TITLE
[Notification] Success notification w/out checkmark

### ISSUE THREAD

**Issue by Berjesty** [telusdigital/tds#463]
## Description

- Our team has used success notification (green) without the checkmark on the billing page - in a scenario where we notify the customer that they have paid already. This way we notify them that they don't need to pay. For this notification we don't always need the the checkmark specially if it's a message we want to resonate with the customer for an action that has been completed in another session. Checkmark would be applicable to the task completed in that instant for the customers. Design is added below for reference, I recommend that we have the css code for this, please let DJL team

## Reproduction Steps

- Click this thing
- Now click this
- Observe this happens

## Reproduction Percentage (if applicable)

- 0/10 times

## Meta

- [ ] TDS version: vX.Y.Z
- [ ] Willing to develop solution
- [ ] Has workaround
- [ ] High impact

## Screenshots
![image](https://user-images.githubusercontent.com/25160096/35641840-4cb5cd10-068f-11e8-8dec-154a087cec66.png)

- Include any relevant screenshots

**Comment by lucylist** [comment]
hey @Berjesty can we just use the general notification/messaging (grey one) treatment for this? the green background is reserved for 'success' notification/feedback. I'm not sure how this type of messaging would be any different from others?

**Comment by Berjesty** [comment]
@lucy its a positive message (success?) that they don't have an amount overdue, this is why we took the green notification treatment. We can go back and change the treatment to grey one for this.

**Comment by ryanoglesby08** [comment]
Hi @Berjesty and @lucylist, following up here. Has this issue been resolved? If so, please close the issue.

**Comment by Berjesty** [comment]
@ryanoglesby08 this issue can be marked as resolved, @lucylist solution was to treat it as a grey notification, TY for the recommendation
