### ISSUE TITLE
TDS css affects non-tds components

### ISSUE THREAD

**Issue by tsungting** [telusdigital/tds#467]
## Description

I have a webpage where I want to use TDS components to follow telus style in part of the page, and in other parts of the page I need the flexibility to not use TDS components (such as tables for html).  I believe as a result of the reset css included in the project, it has removed the list styles, so the unordered list has no bullets, and ordered list has no numbers.

Also `<h1>` is the same size as `<p>`

## Reproduction Steps

1.  Create a component that takes raw html
2.  Include `import styles from '@telusdigital/tds/dist/tds.css';` anywhere in application
3.  Notice list-item style is set to 'none'
4.  Notice h1 - h6 styles have the same style as normal paragraphs

## Reproduction Percentage (if applicable)

- 10/10 times

## Meta

- [ x] TDS version: v1.0.1
- [ x] Willing to develop solution
- [ ] Has workaround
- [ x] High impact

## Screenshots

- Include any relevant screenshots
![image](https://user-images.githubusercontent.com/5641819/35780859-12a9a2c6-09b0-11e8-9671-5d541ea5d2b4.png)

## Description

- Description of the problem

## Recommendation

It would be great if TDS styles would be contained within TDS react components, and not applied to the entire page

## Designs

- Screenshots
- Sketch file

## Meta

- [ ] Currently using TDS version: vX.Y.Z
- [ ] Willing to develop solution
- Has workaround? Yes or no
- Impact: Low, medium, or high

**Comment by ryanoglesby08** [comment]
Thanks for bringing this up!

Yes, at the moment the "tds.css" file contains a small amount of global styles and all the scoped component styles https://github.com/telusdigital/tds/blob/master/guide/getting-started/faq.md#what-global-styles-does-tds-set-on-the-page

We actually already have plans to improve this, which we will be working on in the next month. Our next big initiative is to separate the TDS components into multiple packages, 1 package per component. This will allow consumers to pick and choose which components and styles get included in their application. We will likely also introduce a package for the reset and the global styles, so that you have to choose to include them.

**Comment by ryanoglesby08** [comment]
While you are waiting on that change, are you able to build components or styles to override the global styles from "tds.css"? This is what TDS components do, for example, the `List` components: <https://tds.telus.com/#lists>. Any class name you put on your components will have a higher specificity than the reset, allowing you to fully control the styles of your elements.

**Comment by tsungting** [comment]
I will look into this, the problem I am anticipating is that most of my components actually don't need to be affected by TDS.  I will see if there's an easy way to do this tho.

**Comment by ryanoglesby08** [comment]
@tsungting 

[The latest release of TDS](https://github.com/telusdigital/tds/releases/tag/v2.0.0) splits all TDS components into separate packages. Each component package only contains scoped CSS classes that do not effect any other components on the page.

We have also created a new package called [css-reset](https://www.npmjs.com/package/@tds/core-css-reset) that includes all global CSS. This should allow you to include or not include the global CSS how you see fit in your project.

I believe this addresses your issue, so I'll be closing it. Feel free to reopen if you see any issue.
