### ISSUE TITLE
Request on How to stack a FlexGrid.Row on another FlexGrid.Row

### ISSUE THREAD

**Issue by hamedmam** [telusdigital/tds#468]
## Description

- As we are going to use FlexGrid in new block composition of site-builder, we faced the cases where we need to stack a Row overlapping another Row. We tried to find a solution for that but our experimental solutions did not work well, the example Screenshot is available below. 

## Screenshots

![](https://image.ibb.co/fsiBox/Screen_Shot_2018_02_05_at_4_09_06_PM.png?raw=true)

**Comment by ryanoglesby08** [comment]
Hi @hamedmam,

> we need to stack a Row overlapping another Row

Looking at the screenshot, I am thinking you are referring to the "floating" card when you say "stack a Row"

My first thought for how to lay this out would be something like this:

```jsx
<FlexGrid.Row verticalAlign={bottom}>
  <BigBackgroundImage />
  <FlexGrid.Col span={4} offset={4}>
    <Card>Accessibility...</Card>
  </FlexGrid.Col>
</FlexGrid.Row>
```

And the catch would be that the `BigBackgroundImage` is absolutely positioned or something.

**Comment by hamedmam** [comment]
Thanks that solved it.
