### ISSUE TITLE
How to name TDS component packages?

### ISSUE THREAD

**Issue by ryanoglesby08** [telusdigital/tds#469]
## The main question

TDS will soon start independently versioning the components, meaning each component will become a separate package. We plan on keeping a single repository (a monorepo) and using a tool such as [lerna](https://lernajs.io) to help us manage the multiple package setup.

**What we are wondering is... how to name the component packages?**

## The plot thickens...

We currently publish TDS as a scoped package under the [TELUS Digital npm organization](https://www.npmjs.com/org/telusdigital). What we wanted to do was add another "/" to denote the various components, think `@telusdigital/tds-core/button`. Unfortunately, npm packages can't contain any more slashes after the scope, so that doesn't work. :(

**Brainstorm time: what are the alternatives? What are the patterns for this kind of thing you know of?**

**Comment by yawaramin** [comment]
Seems like `@telusdigital/tds-core-button` would work. One thing I would ask is, can namespacing be minimised. E.g., is `core` necessary? In other words, can there be other kinds of buttons other than core buttons?

**Comment by wintorez** [comment]
I agree with @yawaramin. Maybe you could have one package `@telusdigital/tds-core` which contains general things, like grids, etc. And then `@telusdigital/tds-button` etc. for individual components.

**Comment by ryanoglesby08** [comment]
> E.g., is core necessary?

**Comment by ahmadnassri** [comment]
typing is hard ...

I already claimed `@telus` scope on npm _(and planning to claim the GitHub one)_

we can do `@telus/design-button` or `@telus/core-button` I feel the TDS part is redundant ... especially since Telus is in the scope

**Comment by ahmadnassri** [comment]
I just claimed `@tds` as an org on npm too, so you have that option to debate too

**Comment by ahmadnassri** [comment]
I like these options so far: (can use `@telus` or `@telusdigital` but why not the proper company brand!)

```
@telus/button
@telus/core-button
@tds/button
```

I think regardless omit `tds` from naming to discourage confusion of publishing a "button" separately and to claim that component name within the org scope globally

**Comment by ryanoglesby08** [comment]
@ahmadnassri thanks for the comments. And for rampantly staking claims in npm-land.

> I just claimed @tds as an org on npm too, so you have that option to debate too

Nice that a tds org is on the table too. We had kicked around that idea as it would create a space for future expansion, community components, other tools, etc

**Comment by ahmadnassri** [comment]
I generally hate squatting and squatters, but for `@telus` that's our brand and we should own it, and for `@tds` if we decide to use it, great, if not, I will release it into the wild again!

**Comment by githubjosh** [comment]
I like:
@tds/core-button
@tds/community-analytics-hoc

**Comment by ryanoglesby08** [comment]
Hi everyone, thanks for the comments and suggestions!

We are going to go with @githubjosh's suggestion:

`@tds/core-<component name>`
`@tds/community-<component name>`
