### ISSUE TITLE
Problem with randomized id in Panel.jsx in TDS v0.23.0

### ISSUE THREAD

**Issue by wintorez** [telusdigital/tds#470]
## Description

At the moment, in the `mobility-pdp-evolution` project, we're using v0.23.0 of TDS, along with React 16.2.0. We're also using isomorphic-starter-kit, which means that the initial DOM will be rendered on the server-side and then we use [ReactDOM.hydrate()](https://reactjs.org/docs/react-dom.html#hydrate) to render on the client side.

Now the problem we have is in this particular version of TDS, the Panel.jsx component generates a randomized `id` on `componentWillMount` and use it to set the `aria-control` attribute of one of its subcomponents. This causes the `hyrdrate()` to fail to take over the DOM rendering and is forced to re-render the whole initial DOM again on the client-side, which is not optimal. Right now in our client console, we get the following warning on each render:

```
Warning: Prop `aria-controls` did not match. Server: "i13hukpfz" Client: "c09csk4q4"
```

Upon inspecting the rendered source, we can see this snippet:

```
<button aria-expanded="false" aria-controls="i13hukpfz" class="collapsible-panel__label collapsible-panel__label--collapsed collapsible-panel__label--first">
```

Which shows that the randomized aria-controls value is coming from the TDS collapsible-panel.

## Recommendation

The problematic code snippet can be found at Panel.jsx file line 16:

```
14  class Panel extends Component {
15    componentWillMount() {
16      const id = Math.random().toString(36).substr(2, 9)
17      this.setId(id)
17    }
```

By changing line 16 to `const id = this.props.id || Math.random().toString(36).substr(2, 9)` we will allow consumer of the Panel to set an id for the panel while maintaining backward compatibility for the rest of the users.

Note: at the moment, we don't have the bandwidth to upgrade and test our TDS to ^1.0.0, so applying this change will require the creation of v0.23.1.

**Comment by ahmadnassri** [comment]
latest supported versions are `1.x` and `34.x` we would only apply changes to those.

what's the barrier for not upgrading?

**Comment by wintorez** [comment]
@ahmadnassri Thanks for your comment. Let me try upgrading to 34.x and get back to you.

**Comment by wintorez** [comment]
@ahmadnassri I upgraded to v0.34.x as you suggested and unfortunately, ran in a whole range of regression errors. Since we'll be entering a Hackathon next week, I was hoping I'd be able to eliminate that warning without impacting the rest of the application by upgrading to a patched v0.23.x.

If that's not possible, then we'll stick to our upgrade plan to v1.0.x in the future.

**Comment by ryanoglesby08** [comment]
Hi @wintorez, yes, I'll echo @ahmadnassri and say that we do not plan on releasing patches to v0.230. Officially we support v0.34 and v1.0, and will release patches to both versions.

The specific bug you pointed out was fixed in [v0.30.0 of TDS](https://github.com/telusdigital/tds/releases/tag/v0.30.0) so you could also try updating to that one, though there was a small bug in that version too for IE11.

**Comment by wintorez** [comment]
@ryanoglesby08 Thank you for your suggestion. Unfortunately both v0.30.0 and v0.33.1 broke our regression tests :(

**Comment by wintorez** [comment]
@ahmadnassri & @ryanoglesby08 I managed to patch the problem locally by adding following snippet before using `ExpandCollapse.Panel` which effectively patches the problem locally (Inheritance FTW):

```
ExpandCollapse.Panel = class extends ExpandCollapse.Panel {
  componentWillMount() {
    const id = this.props.id || Math.random().toString(36).substr(2, 9);
    this.setId(id);
  }
};
```

**Comment by ahmadnassri** [comment]
not really related: I'm planning an "upgrade and break dependencies party" in the near future ... lets see if we can get everybody closer to latest deps!
