### ISSUE TITLE
Chevron icons get cropped while moving

### ISSUE THREAD

**Issue by alexandramfedyk** [telusdigital/tds#479]
Description

Hover over a chevron link and look at the chevron icon. As its moving, it gets clipped. It is more pronounced in the left facing chevron.

Defect Priority: Medium
Defect Severity: Moderate
Testing Environment: Production
Method of discovery: Manual
Defect Nature: Visual

**Comment by ryanoglesby08** [comment]
Unable to reproduce. Closing.
