### ISSUE TITLE
[Card] In IE long text strings do not wrap [IE browser ONLY]

### ISSUE THREAD

**Issue by kgrimsley** [telusdigital/tds#504]
## Description

When using the Card component, if we have a long string (inside a <Paragraph></Paragraph>), it does not wrap when it gets to the border of the card. This behaviour only happens in Internet explorer.

## Reproduction Steps

- Build a Card with a very long string. This can even be done through the TDS documentation page, through their sample code. For example:
```
<Card>
  <Box between={4} dangerouslyAddClassName="docs_align-flex-start">
    <Box between={3}>
      <Heading level="h2">Need a hand?</Heading>
      <Paragraph>
        Ready to order? Have a question? We'll get back o you, with volume discounts available to
        larger accounts. I have a really long message that should wrap but becasue I am in internet explorer it does not.  
      </Paragraph>
    </Box>
  </Box>
</Card>
```

## Reproduction Percentage (if applicable)

- 10/10 times

## Meta

- [ ] TDS version: v0.32.0, 1.0.3
- [ ] High impact

## Screenshots

*Internet Explorer:*
<img width="1398" alt="screen shot 2018-03-02 at 10 53 17 am" src="https://user-images.githubusercontent.com/7525668/36907967-f979db2e-1e07-11e8-970b-0a5c3017fed2.png">

*Chrome:*
<img width="1384" alt="screen shot 2018-03-02 at 10 54 26 am" src="https://user-images.githubusercontent.com/7525668/36908061-3a3aa904-1e08-11e8-8a4a-f056508ce0e2.png">

**Comment by theetrain** [comment]
This issue has been resolved in our documentation and will be later deployed.

**Comment by ryanoglesby08** [comment]
@kgrimsley we have deployed this fix to the production docs site. Can you confirm that the issue has been fixed?

**Comment by theetrain** [comment]
I confirmed this to be resolved on IE11

![image](https://user-images.githubusercontent.com/12798751/37534677-dae3ecda-291b-11e8-8904-0afef5652e29.png)
