### ISSUE TITLE
[Notification] Make error style meet WCAG AAA compliance

### ISSUE THREAD

**Issue by lucylist** [telusdigital/tds#506]
## Description

The current error feedback indicator component isn't AAA accessible. It's currently 5.56:1 and needs to be 7:1
https://webaim.org/resources/contrastchecker/?fcolor=C12335&bcolor=FFF6F8

## Recommendation

Make the text shark grey #2A2C2E like the input feedback component.

## Designs
<img width="924" alt="screen shot 2018-03-02 at 4 35 49 pm" src="https://user-images.githubusercontent.com/17018330/36922994-cc297bf4-1e37-11e8-9af6-1530ea00e412.png">

<img width="921" alt="screen shot 2018-03-02 at 4 33 53 pm" src="https://user-images.githubusercontent.com/17018330/36922934-983a1614-1e37-11e8-91db-6466c6b58129.png">

## Meta

- [ ] Currently using TDS version: vX.Y.Z
- [ ] Willing to develop solution
- [ ] Has workaround
- [ ] High impact

**Comment by ryanoglesby08** [comment]
Fixed in v0.34.11, v1.0.10, and `@tds/core-notification@1.1.0`
