### ISSUE TITLE
[FlexGrid] Padding on right side of page in mobile view

### ISSUE THREAD

**Issue by slawlertelus** [telusdigital/tds#507]
## Description
* There is a small, but noticeable padding on the right side of the page when in mobile view. I tested this with Chrome on both my phone (LGv20) and Mac laptop.

## Reproduction Steps

* Go to Billing or PAPN pages and set browser's resolution to 375x842.
* Click and drag the screen to scroll right.
* See a screenshot of this attached below.

## Reproduction Percentage (if applicable)

* 10/10 times

## Meta

* TDS version: v1.0.3, v1.0.4
* Willing to develop solution: No
* Has workaround: No
* High impact: No

## Screenshots
<img width="426" alt="screen shot 2018-03-06 at 3 40 35 pm" src="https://user-images.githubusercontent.com/32268010/37057257-c69d89c6-2154-11e8-81cc-8c93ba3afd34.png">
<img width="401" alt="screen shot 2018-03-06 at 3 42 15 pm" src="https://user-images.githubusercontent.com/32268010/37057326-01aa9518-2155-11e8-9bb7-687c53bba4a1.png">

Note that the width of the back to billing link is more than the screen width set in the resolution.

**Comment by ryanoglesby08** [comment]
> Go to Billing or PAPN pages and set browser's resolution to 375x842.

Hi @slawlertelus, do you have a direct/unauthenticated URL I can visit? Or can you reproduce this on the [TDS component catalogue](https://tds.telus.com/components/index.html)?

**Comment by ryanoglesby08** [comment]
May be related to #518 . Need to confirm that.

**Comment by theetrain** [comment]
This has been fixed in 0.34.8, 1.0.7, and @tds/core-flex-grid@1.1.0
