### ISSUE TITLE
[ExpandCollapse] Customizable ExpandCollapse Component

### ISSUE THREAD

**Issue by lxingtelus** [telusdigital/tds#528]
## Description

* Design based on usability testing suggested collapsing notification panel with custom header for panel.
* ExpandCollapse component should be more generalized to enable customization of the chevron and header.

## Recommendation

* Currently the ExpandCollapse component only allows string child as header, it would be nice to be able to use components such as `<Notification />` as header.
* It also only allows primary chevron, would be great to have a prop to control the chevron styles and perhaps position of the chevron.

## Designs

![image](https://user-images.githubusercontent.com/30837029/37615738-5bd693e6-2b84-11e8-9189-55d9a77c4e5a.png)

## Meta

* TDS version: v1.0.4
* Willing to develop solution: Tight timeline
* Has workaround: No
* High impact: Yes

**Comment by lucylist** [comment]
Hey @lxingtelus thanks for submitting this request! I spoke to @Berjesty on the design and she will be sharing it with the design leads so that everyone is onboard with this pattern. From there, we can then move it towards potentially being contributed in to TDS.

**Comment by ryanoglesby08** [comment]
Let's circle back on this after the design leads chat through it.

Looking forward a little bit, I think the way to go could be:

1. Create a more generic `Collapsible` component that encapsulates only the behaviour of "a component that opens and closes some content". This component would not have any restrictions on the content of the "thing you click" and the content. It would be part of tds-core.
2. This new component being requested could then be created on top of the new Collapsible component and potentially contributed to tds-community
3. The current ExpandCollapse component could be refactored to be built on top of the new Collapsible component too.

**Comment by lucylist** [comment]
hey @lxingtelus, @Berjesty shared this design at the design leads meeting last Friday and we concluded that this pattern and interaction isn't something that would be widely used across multiple tribes. 

So for now we will keep the notification component generic to not include the expand and collapse (and vice versa).

closing this issue until any future use cases may come up.
