### ISSUE TITLE
[Notification] Accept an Icon as Props

### ISSUE THREAD

**Issue by saxtron** [telusdigital/tds#530]
## Description

The Notification component uses icons for the success and error variants, but it is difficult to use an icon otherwise.  For example a design for My Account Usage called for a Notification similar to the branded variant, but with an icon.
The design can be seen here (...hopefully): https://telus.invisionapp.com/d/main#/console/13507983/282372732/preview

## Recommendation

I am recommending that the Notification component accept an icon as an optional prop.
This prop would override the default icons for the success and error variants, and be a way to add icons to variants that otherwise don't have them.  If this props isn't supplied, the behaviour would be as it is now (success and error variants get icons, others do not).

Without investigating too much, I would think the value of this icon prop would be one of the symbol enums used by the Icon TDS components.

This will make code easier to write, as I had to do a lot of snowflake coding to hack an icon into a Notification component using the branded variant.
See for reference:
https://github.com/telusdigital/my-account-usage/pull/24/commits/4e1eeab0c7d5ec550d96721992c6e1a7f884ea0b#diff-a95de90fcda49e296f7e6bbcb92022ab
https://github.com/telusdigital/my-account-usage/pull/24/commits/4e1eeab0c7d5ec550d96721992c6e1a7f884ea0b#diff-4d142ef5e79d6f015e251e1f55e91353

## Meta

* TDS version: v1.0.0
* Willing to develop solution: YES!!!!
* Has workaround: I guess...?
* High impact: I don't know

**Comment by lucylist** [comment]
hey @saxtron can you relink the designs? it doesn't seem to be working. Would like to better understand the use case so we can see where we can help.

**Comment by saxtron** [comment]
Here's the InVision link: https://telus.invisionapp.com/d/main#/console/13507983/282430616/preview
You'll have to page left or right to see the different use cases.

Here's the JIRA ticket linking to the designs: https://telusdigital.atlassian.net/browse/NUT-1422

@stellambaka and Daniel Genuardi are working on the designs, so if you still don't have access please reach out to them.

Let me know if there's any other questions!  More than happy to chat and solution together.

**Comment by lucylist** [comment]
hey @saxtron will be speaking to Stella and Daniel about the design. I'd like to see if we can use what we currently have without modifying the notification types. Perhaps introducing subtle animation/motion to draw focus to the notifications without changing the style.

My concern is that if we introduce the icon prop that in the future we can start getting various icons for various messaging and it could get a little messy and inconsistent with all the variants.

<img width="1392" alt="screen shot 2018-03-22 at 8 53 03 am" src="https://user-images.githubusercontent.com/17018330/37772463-17945450-2db1-11e8-95cb-fb670f91ceaf.png">

**Comment by saxtron** [comment]
Perhaps a solution could be to add a new `warning` variant to the Notification component which has the styling required for the above design (aside from the dismiss X, which is covered in #423).
I agree, opening up an icon prop could get messy and lead to inconsistency.  Adding a warning variant makes the component more flexible while still keeping things consistent.

As a real-world example, right now I'm using the `branded` variant to achieve the above "Warning" message, which feels a little clunky.

**Comment by lucylist** [comment]
yeah, i think if this becomes an issue where it's something that you guys require totally open to going that route. spoke to @stellambaka and we're going to try the generic for now and see if it works and revisit if we learn that it's not working.

doing the dismiss #423 would be amazing though! :)

**Comment by lucylist** [comment]
closing this issue as per discussions with @saxtron and @stellambaka

- team will use TDS notification components as is and will revisit if it becomes an issue
- team will build out #423 and potentially contribute! :)
