### ISSUE TITLE
Expand component indentation

### ISSUE THREAD

**Issue by Berjesty** [telusdigital/tds#569]
## Description

* when expanded the sub-charges on the bill don't align with the rest of the content, apparent usability of this component suggest is allowing to right align the charges with the rest of them on the page

## Designs

* Screenshots
![image](https://user-images.githubusercontent.com/25160096/38441683-96e397a8-39b3-11e8-9da8-c663019f7677.png)

* Invision file
https://telus.invisionapp.com/d/main/#/console/12448253/274219632/preview

## Meta

* TDS version: v1.0
* Willing to develop solution: Yes
* Has workaround: Yes
* High impact: No

**Comment by donnavitan** [comment]
Hello @Berjesty we're currently working on an update to the TDS which will address this issue when working with design in Sketch. Otherwise, the code component is working as intended (for reference: https://tds.telus.com/components/index.html#expandcollapse).

**Comment by Berjesty** [comment]
Great thanks @donnavitan
